import { Geist, Geist_Mono , Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import localFont from "next/font/local";



 const poppins = Poppins({
  weight:["100","200","400","500","600","800"]
})
export const FontBangla = localFont({
  // Move up two levels: out of 'app', out of 'src', then into 'public'
  src: "../../public/fonts/mayaboti-normal.ttf", 
});

export const metadata = {
  title: "Hero KiDz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     
    >
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2  md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-320px)]">
           {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>

      </body>
    </html>
  );
}
